food_finder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("food_finder_app.urls")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(),name='f_f_logout'),
]

food_finder_app/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LogoutView
from . import views
from .views import EventDetailView

app_name = "food_finder_app"
urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name = "index"),
    path("accounts/", include("allauth.urls")),
    path("logout", LogoutView.as_view()),
    path("map", views.map, name="map"),
    path("events/", views.events, name="events"),
    path("create_event/", views.create_event, name="create-event"),
    path("approval/", views.approval, name = "approval"),
    path('events/details/<int:pk>', EventDetailView.as_view(), name="event-detail"),
]

templates/admin.html
{% load socialaccount %}
<html>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<body>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="display-4">Welcome to Free Food Finder</h3>
    {% if user.is_authenticated %}
    <p class="lead">You are logged in as {{ user.username }} at email address {{ user.email }}</p>
    <p>You are logged in as an event leader(admin)</p>
    {% else %}
    <p class="lead">Log in to get started</p>
    <a class="btn btn-primary btn-lg" href="{% provider_login_url 'google' %}" role="button">Login with Google</a>
    {% endif %}
  </div>
</div>

</body>

templates/admin_approval.html
<!--  https://www.youtube.com/watch?v=FzV_Py68Y_I-->
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
<style>
       body {
        background-color: #e0eefa;
      }


        .jumbotron {
            background-color: #ffffff;
            padding: 2rem;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .navbar {
            background-color: #aabfe1;
        }

        .navbar-brand {
            font-weight: bold;
        }

        .btn-floating:hover {
            background-color: rgba(72, 118, 244, 0.443);
        }

        .btn-floating {
            border: 1px solid #4978ed;
        }

        .btn-light {
            background-color: #aabfe1;
        }
    h3 {
        padding-bottom: 10px;
    }
</style>
<body>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3>Admin Approval</h3>
    <h5>Check the box to approve an event and hit 'Update Approval' to save!</h5>

    <form action = "" method="POST">
        {% csrf_token %}

    <button class = 'btn btn-light' type = 'submit' >Update Approval</button>
        <br><br>
    <table class = "table table-striped table-hover table-bordered">
        <thread>
            <tr>
                <th scope = "col">Event Name</th>
                <th scope = "col">Approved</th>
            </tr>
        </thread>
        <tbody>
            {% for event in event_list %}
            <tr>
                <td><a href="{% url 'food_finder_app:event-detail' event.id %}"> {{ event.event_title }}</a></td>
                <td>
                    {% if event.approved %}
                    <div class = "form-check">
                        <input class = "form-check-input" type = "checkbox" checked="checked" value = {{event.id}} name="boxes">
                    </div>
                    {% else %}
                    <div class = "form-check">
                        <input class = "form-check-input" type = "checkbox" value = {{event.id}} name="boxes">
                    </div>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<br/>

    </form>
        </div></div>
<br/>
<br/>
</body>
</html>
{% endblock %}

templates/base.html
  <head>
<!--Links and script files from:
      https://stackoverflow.com/questions/54207669/hamburger-menu-not-opening-on-bootstrap
      Used to get the split screen smaller navbar to be reactive -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


    <style>
      .bigger-text {
        font-size: 35px; 
        }       
        body {
            background-color: #e0eefa;
        }
      

        .navbar2 {
            background-color: #aabfe1;
        }

        .navbar-brand {
          font-weight: 500;
        }
        .navbar-nav .nav-item:hover .nav-link {
          font-weight: bolder;
        }
        .navbar-nav .nav-item.active .nav-link {
            color: #fff;
            
}

        .btn-floating:hover {
            background-color: rgba(72, 118, 244, 0.443);
        }

        .btn-floating {
            border: 1px solid #4978ed;
        }

        .btn-floating:hover {
            background-color: #4978ed;
        }
    
    </style>

</head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-light navbar2">
  <a class="navbar-brand" href="{% url 'food_finder_app:index' %}">Free Food</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'food_finder_app:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'food_finder_app:create-event' %}">Create Event <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food_finder_app:events' %}">Events List <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'food_finder_app:map' %}">Events Map <span class="sr-only">(current)</span></a>
      </li>
        {% if "Admins" in user.groups.all.0.name %}
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'food_finder_app:approval' %}">Approve Events <span class="sr-only">(current)</span></a>
      </li>
        {% endif %}
    </ul>
    {% if user.is_authenticated  %}
    <ul class="navbar-nav">
      <li class="nav-item">
          <button class="btn btn-sm btn-light" style="background-color: #cfdaed;">
              <a href="{% url 'f_f_logout' %}" class="text-dark" style="text-decoration: none;">
                  <i class="fab fa-google"></i>
                  Log Out
              </a>
          </button>
      </ul>
    {%endif%}

    <!-- <span class="navbar-text">
       {% if user.is_authenticated %}
            <p class="lead">@{{user.username}}</p>
            <p class="lead">{{user.groups.all}}</p>
            {% if "Admins" == user.groups.all.0 %}
                <p class="admin">@admin</p>
             {% endif %} -->
        <!-- {% endif %}
    </span>-->
  </div>
</nav>
  </head>

  {% block content %}

{% endblock content %}

</body>
</html>

templates/create_event.html
<!doctype html>
{% extends 'base.html' %}
{% load static %}
<!--
 @license
 Copyright 2019 Google LLC. All Rights Reserved.
 SPDX-License-Identifier: Apache-2.0
-->
<html>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{% block content %}
<head>
  {{ form.media }}
  <style>
    body, .jumbotron {
        background-color: #e0eefa;
      }

    .center-box {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
     }

    .form-box {
        background-color: #ffffff;
        padding: 15px;
        border-radius: 20px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        width: 50%;
        margin-top: 50px;
        margin-bottom: 100px;
    }

    ul.horizontal_choice {
      display: flex;
      flex-direction: row;
      list-style-type: none;
    }

    ul.horizontal_choice li {
      margin-right: 20px;
    }

    div.mb-3 label.form-label {
      font-weight: bold;
      margin-right: 3rem;
    }

    div.form-row-times {
      display: flex;
      flex-direction: column;
      max-width: 15rem;
    }

    div.form-row-addy {
      display: flex;
      flex-direction: column;
      max-width: 35rem;
    }
  </style>

<body>

<div class="center-box">
    <div class="form-box">
        <form method="post">
            {% csrf_token %}
            <h2 class="text-center mb-4">Create Event</h2>
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <div class="mb-3">
              <label for="{{ form.event_title.id_for_label }}" class="form-label">Event Title</label>
              {{ form.event_title }}
              {% for error in form.event_title.errors %}
                <p class="text-danger">{{ error }}</p>
              {% endfor %}
            </div>

            <div class="mb-3">
              <label for="{{ form.event_description.id_for_label }}" class="form-label">Event Description</label>
              {{ form.event_description}}
              {% for error in form.event_description.errors %}
                <p class="text-danger">{{ error }}</p>
              {% endfor %}
            </div>

            <div class="mb-3">
              <div class="form-row-addy">
                <label for="{{ form.address.id_for_label }}" class="form-label">Event Address</label>
                {{ form.address}}
              </div>
            </div>

            <div class="mb-3">
              <div class="form-row-times">
                <label for="{{ form.event_date.id_for_label }}" class="form-label">Event Start Date & Time</label>
                {{ form.event_start_date}}
              </div>
            </div>

            <div class="mb-3">
              <div class="form-row-times">
                <label for="{{ form.event_duration.id_for_label }}" class="form-label">Event End Date & Time</label>
                {{ form.event_end_date}}
              </div>
            </div>

            <div class="mb-3">
              <label for="{{ form.available_to_years.id_for_label }}" class="form-label">Event Availability</label>
              {{ form.available_to_years}}
            </div>

            <button type="submit" class="btn btn-primary btn-block mt-4 btn-light">Submit</button>
        </form>
    </div>
</div>
</body>
</html>

<!-- 
<div class="container d-flex align-items-center">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-light">Submit</button>
  </form>
</div> -->


<!-- <form method="post" class="form">
    {% csrf_token %}
     {{ form.as_p }}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        {{ form.username.errors }}
    </div>
    <div class="form-group">
        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
        {{ form.password.errors }}
    </div>
    
</form> -->

{% endblock content %}

templates/event_detail.html
<!doctype html>
{% extends 'base.html' %}

{% block content %}
<style>
      <style>
      .bigger-text {
        font-size: 35px; 
}
        body{
            background-color: #e0eefa;
        }
        

        .jumbotron {
            background-color: #ffffff;
            padding: 2rem;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .navbar {
            background-color: #aabfe1;
        }

        .navbar-brand {
            font-weight: bold;
        }

        .btn-floating:hover {
            background-color: rgba(72, 118, 244, 0.443);
        }

        .btn-floating {
            border: 1px solid #4978ed;
        }

        .btn-floating:hover {
            background-color: #4978ed;
        }
    div {
        padding-bottom: 10px;
    }

    </style>
<html>

<body>
<!--<div class="jumbotron jumbotron-fluid">-->
<!--  <div class="container">-->
<!--    <h3 class="display-4">Free Food Events</h3>-->
<!--  </div>-->
<!--</div>-->

<div class="jumbotron jumbotron-fluid">
  <div class="container">
  <h1 style ="padding-top: 30px;">{{ object.event_title }}</h1> <br>
            <b>Event description:</b> {{ event.event_description }}<br>
             <b>This event is available to:</b> {{ academic_years }}<br>
              <b>Event start time:</b> {{ event.event_start_date }}<br>
                <b>Event end time:</b> {{ event.event_end_date }}<br>
                <b>Address:</b> {{ address }}<br>
  </div>
</div>


</body>
</html>
{% endblock %}

templates/events.html
<!doctype html>
{% extends 'base.html' %}

{% block content %}

<html>

<style>
    body {
        background-color: #e0eefa;
      }
      
        
        .jumbotron {
            background-color: #ffffff;
            padding: 2rem;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .navbar {
            background-color: #aabfe1;
        }

        .navbar-brand {
            font-weight: bold;
        }

        .btn-floating:hover {
            background-color: rgba(72, 118, 244, 0.443);
        }

        .btn-floating {
            border: 1px solid #4978ed;
        }

        .btn-floating:hover {
            background-color: #4978ed;
        }
    h3 {
        padding-bottom: 10px;
    }
  </style>
<body>
  <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="display-4">Free Food Events Happening Now</h3>
    {% if cur_events%}
    <ul>
    {% for event in cur_events %}
        {% if event.approved %}
          <a href="{% url 'food_finder_app:event-detail' event.id %}" class="list-group-item list-group-item-action" style="width: 240px;" aria-current="true">
              <div class="d-flex w-100 justify-content-between text-primary">
                <h5 class="mb-1 "> {{event.event_title}} </h5>
              </div>
            <p class="mb-1 text-dark"> {{event.event_start_date}}</p>
<!--              <p class="mb-1 text-dark"> {{event.event_end_date}}</p>-->
          </a>
        {% else %}
                <p>No events are available.</p>

        {% endif %}
    {% endfor %}
    </ul>
    {% else %}
        <p>No events are available.</p>
    {% endif %}
</div>
</div>
    <div class="jumbotron jumbotron-fluid">
  <div class="container">
      <h3 class="display-4">Free Food Events Coming Up</h3>
    {% if future_events%}
    <ul>
    {% for event in future_events %}
        {% if event.approved %}
          <a href="{% url 'food_finder_app:event-detail' event.id %}" class="list-group-item list-group-item-action" style="width: 240px;" aria-current="true">
              <div class="d-flex w-100 justify-content-between text-primary">
                <h5 class="mb-1 "> {{event.event_title}} </h5>
              </div>
            <p class="mb-1 text-dark"> {{event.event_start_date}}</p>
<!--              <p class="mb-1 text-dark"> {{event.event_end_date}}</p>-->
          </a>
        {%else%}
        <p>No events are available.</p>
        {%endif%}
    {% endfor %}
    </ul>
    {% else %}
        <p>No events are available.</p>
    {% endif %}
    
</div>
</div>

</body>
</html>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% block content %}
    <style>
      .bigger-text {
        font-size: 35px; 
}
        body,
        .jumbotron {
            background-color: #e0eefa;
        }
        
        .jumbotron {
            background-color: #ffffff;
            padding: 2rem;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .navbar {
            background-color: #aabfe1;
        }

        .navbar-brand {
            font-weight: bold;
        }

        .btn-floating:hover {
            background-color: rgba(72, 118, 244, 0.443);
        }

        .btn-floating {
            border: 1px solid #4978ed;
        }

        .btn-floating:hover {
            background-color: #4978ed;
        }
    </style>
</head>



<body style="position: relative;">

    {% load socialaccount %}

    <div class="container mt-5" style="display: flex; flex-direction: column; min-height: 100vh; justify-content: center; align-items: center;">
      <div class="jumbotron jumbotron-fluid">
          <div class="container">
              <h3 class="display-4 text-center font-weight-bold">Welcome to Free Food Finder</h3>
              {% if user.is_authenticated %}
              <p class="lead text-center">You are logged in as {{ user.username }} at email address {{ user.email }}</p>
              {% if "Admins" in user.groups.all.0.name %}
              <p class="text-center">You are logged in as an event organizer (admin)</p>
              {% endif %}
              {% else %}
              <p class="lead text-center bigger-text">Log in to get started</p>
              <div class="text-center"> 
                  <button class="btn btn-outline-info btn-floating">
                      <a href="{% provider_login_url 'google'%}">
                          <i class="fab fa-google"></i>
                          Login with Google
                        </a>
                      </button>
                      <div class="center-buttons mb-4"></div>
                  </div>
                  {% endif %}
              </div>
          <div></div>

            <!-- Buttons from https://mdbootstrap.com/learn/mdb-foundations/bootstrap/icons-and-lists/  -->
            <div class="text-center">
                <div class="center-buttons">
                    <a href="{% url 'food_finder_app:create-event' %}">
                        <button type="button" class="btn btn-outline-success btn-floating"
                            data-mdb-ripple-color="dark" style="border-color: rgb(73, 120, 237);">
                            <i class="far fa-pen-to-square text-primary me-2"></i>
                        </button>
                    </a>
                    <a href="{% url 'food_finder_app:events' %}">
                        <button type="button" class="btn btn-outline-success btn-floating"
                            data-mdb-ripple-color="dark" style="border-color: rgb(73, 120, 237);">
                            <i class="fas fa-clipboard-list text-primary me-2"></i>
                        </button>
                    </a>
                    <a href="{% url 'food_finder_app:map' %}">
                        <button type="button" class="btn btn-outline-success btn-floating"
                            data-mdb-ripple-color="dark" style="border-color: rgb(73, 120, 237);">
                            <i class="fa-solid fa-map-location-dot text-primary me-2"></i>
                        </button>
                    </a>

                </div>
            </div>
        </div>
    </div>

</body>

</html>
{% endblock content %}

templates/map.html
<!doctype html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--
 @license
 Copyright 2019 Google LLC. All Rights Reserved.
 SPDX-License-Identifier: Apache-2.0
-->
<html>
  
    <title>Add Map</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <link rel = "stylesheet" href = "{% static 'food_finder_app/style.css' %}">

    <script>
    let map
    // https://www.youtube.com/watch?v=sasx2ppol5c
     function initMap(){

        var locations = {{ event_list|safe }};
        var firstLocation = locations[0];
        var infoWindow = [];

        map = new google.maps.Map(document.getElementById("map"),{
            center: { lat: 38.03537, lng: -78.50335 },
            zoom: 14.5,
        }
        );


        locations.forEach(function (location){
            var marker = new google.maps.Marker({
                position: {lat: location.lat, lng: location.long},
                map: map,
                title: location.name
            });

            var infowindow = new google.maps.InfoWindow({
                minWidth: 200,
            });

            infoWindow.push(infowindow)
            var details_link = "/events/details/" + location.event_id;
            var name = location.name;
            var description = location.description;

            marker.addListener('click', function(){
                infoWindow.forEach(function(iw){

                    iw.close();
                });

                infowindow.open(map, marker)

                infowindow.setContent(
                '<h3>' + name + ' </h3>'+
                '<p>' + description + ' <p>'+
                '<p><div><a href=" ' + details_link + ' ">Event Details</a></div></p>');


            });

        });
    }

    window.initMap = initMap

</script>



        {% if event_list%}
         <h3>Map of Free Food</h3>
        <div id="map">
        <script async
                src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&callback=initMap">
            </script>
        </div>

        {% else %}

       <div class="container">
                   <h3>Map of Free Food</h3>
            <p>There are no free food events at this time</p>
            <button type="button" class="btn btn-light" >
                <a href = "{% url 'food_finder_app:create-event' %}">Add an event</a>
            </button>
       </div>
        {% endif %}

  </body>
</html>
{% endblock %}